#   conda env create -f environment.yml
name: HiC-Pro_v3.0.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7.6
  - scipy=1.4.1
  - numpy=1.18.1
  - iced=0.5.8
  - bx-python=0.8.8
  - pysam=0.15.4
  - cooler=0.8.6

  - r-base=3.6.3
  - r-ggplot2=3.1.1
  - r-rcolorbrewer=1.1_2
  - r-gridbase=0.4_7
  - conda-forge::tbb=2020.2=hc9558a2_0
  - bowtie2=2.3.5
  - samtools=1.9
  - multiqc=1.8
